### ISSUE TITLE
transact for sqlite

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/lighthouse#1]
Hey, JFYI, sqlite as of 3.25 also supports postgres' ON CONFLICT DO syntax, which allows for upserting and therefore transacting. I implemented this yesterday for python, if you're curious you can rifle through the code and steal what you want. Most of it is inspired by coast anyway ;)

https://gist.github.com/mgerlach-klick/0044a0e7e98b20002e967d495a8d79c7#file-db-py-L65

**Comment by swlkr** [comment]
Oh interesting, yeah that’s next up, I might call it upsert or something though, I kind of changed “transact” to take a vector of sql 😅

**Comment by swlkr** [comment]
Just going to close this. I'm open to PRs for this though!
