### ISSUE TITLE
defq function

### ISSUE THREAD

**Issue by jgallinari** [coast-framework/lighthouse#5]
Hi,

`defq` as defined is not a macro but a function.
However you use `~` in its body. I saw that when trying to use it unsuccessfully.
Based on your code in [https://github.com/coast-framework/coast](https://github.com/coast-framework/coast), something like this works better for me :
```
(defmacro defq
  ([conn-pool n filename]
   `(let [q-fn# (lighthouse.defq/query-fn ~conn-pool (assoc (lighthouse.defq/query ~(str n) ~filename) :ns *ns*))]
      (lighthouse.defq/create-root-var ~(str n) q-fn#)))
  ([conn-pool filename]
   `(lighthouse.defq/query-fns ~conn-pool ~filename)))
```

Any opinion on that?

Thanks,
jerome

**Comment by swlkr** [comment]
Hm that’s definitely a lot better. Huge oversight on my part.

I definitely need to bring over some of the coast db connection stuff to this lib.

But yeah if you don’t get around to a PR, I’ll change `defq` to what you have here
